name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.2
  firebase_messaging: ^9.1.0

  http: ^0.13.0

dev_dependencies:
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
